### ISSUE TITLE
Unable to summarize results on group w/ 0 unique QRPs

### ISSUE THREAD

**Issue by rlvoyer** [socrata/arcs#34]
```sh
(arcs)➜  arcs git:(master) ✗ python arcs/summarize_results.py 47 48 -D 'postgresql://disco_stu:Eac3ZktRlrLDRTiZY6RN66V6@disco-storage-prod.cxp7ndn7xnkv.us-west-2.rds.amazonaws.com:5432/disco_ball'
Traceback (most recent call last):
  File "arcs/summarize_results.py", line 230, in <module>
    main(args.db_conn_str, args.group_1_id, args.group_2_id)
  File "arcs/summarize_results.py", line 201, in main
    group_stats = stats(data_df, ideals_df)
  File "arcs/summarize_results.py", line 154, in stats
    ndcgs_at_5 = group_ndcgs(judged_data, ideals, 5)
  File "arcs/summarize_results.py", line 90, in group_ndcgs
    ndcgs_df = per_query_ndcg(judged_group_df, ideals, ndcg_at)
  File "arcs/summarize_results.py", line 61, in per_query_ndcg
    "dcg": grouped.apply(query_dcg).reset_index()[0],
  File "/Users/robertvoyer/Envs/arcs/lib/python2.7/site-packages/pandas/core/frame.py", line 1914, in __getitem__
    return self._getitem_column(key)
  File "/Users/robertvoyer/Envs/arcs/lib/python2.7/site-packages/pandas/core/frame.py", line 1921, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/robertvoyer/Envs/arcs/lib/python2.7/site-packages/pandas/core/generic.py", line 1090, in _get_item_cache
    values = self._data.get(item)
  File "/Users/robertvoyer/Envs/arcs/lib/python2.7/site-packages/pandas/core/internals.py", line 3102, in get
    loc = self.items.get_loc(item)
  File "/Users/robertvoyer/Envs/arcs/lib/python2.7/site-packages/pandas/core/index.py", line 1692, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
  File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
  File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
KeyError: 0
```

**Comment by rlvoyer** [comment]
https://github.com/socrata/arcs/pull/35
